targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
